/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjecthealthRouteImport } from './routes/projecthealth'

const ProjecthealthRoute = ProjecthealthRouteImport.update({
  id: '/projecthealth',
  path: '/projecthealth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/projecthealth': typeof ProjecthealthRoute
}
export interface FileRoutesByTo {
  '/projecthealth': typeof ProjecthealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/projecthealth': typeof ProjecthealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/projecthealth'
  fileRoutesByTo: FileRoutesByTo
  to: '/projecthealth'
  id: '__root__' | '/projecthealth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProjecthealthRoute: typeof ProjecthealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projecthealth': {
      id: '/projecthealth'
      path: '/projecthealth'
      fullPath: '/projecthealth'
      preLoaderRoute: typeof ProjecthealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProjecthealthRoute: ProjecthealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
